apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
      nodePort: 30007
  selector:
    app: echo-server
  type: NodePort
